################################
## Airflow Ingress
#################################
{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-airflow-ingress
  labels:
    tier: airflow
    component: airflow-ingress
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    kubernetes.io/tls-acme: {{ eq .Values.ingress.acme true | quote }}
    nginx.ingress.kubernetes.io/custom-http-errors: "403,404,502,503"
  {{- if .Values.ingress.auth.enabled }}
    nginx.ingress.kubernetes.io/auth-url: https://houston.{{ .Values.ingress.baseDomain }}/v1/authorization
    nginx.ingress.kubernetes.io/auth-signin: https://app.{{ .Values.ingress.baseDomain }}/login
    nginx.ingress.kubernetes.io/auth-response-headers: authorization, username, email
  {{- end }}
spec:
  tls:
  {{- if .Values.ingress.acme }}
    - secretName: {{ .Release.Name }}-airflow-tls
  {{- else if .Values.ingress.tlsSecretName }}
    - secretName: {{ .Values.ingress.tlsSecretName }}
  {{ else }}
    - secretName: ~
  {{- end }}
      hosts:
        - {{- include "airflow_url" . | indent 1 }}
{{- if eq .Values.executor "CeleryExecutor" }}
        - {{- include "flower_url" . | indent 1 }}
{{- end }}
  rules:
    - host: {{- include "airflow_url" . | indent 1 }}
      http:
        paths:
          - path: /deployments/{{ .Release.Name }}/airflow
            backend:
              serviceName: {{ .Release.Name }}-webserver
              servicePort: airflow-ui
{{- if eq .Values.executor "CeleryExecutor" }}
    - host: {{- include "flower_url" . | indent 1 }}
      http:
        paths:
          - path: /deployments/{{ .Release.Name }}/flower
            backend:
              serviceName: {{ .Release.Name }}-flower
              servicePort: flower-ui
{{- end }}
{{- end }}
