################################
## Kube State Role/ClusterRole
#################################
{{- $singleNamespace := .Values.global.singleNamespace }}
{{- if .Values.global.rbacEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if $singleNamespace }}Role{{ else }}ClusterRole{{ end }}
metadata:
  name: {{ template "kube-state.fullname" . }}
  labels:
    tier: monitoring
    component: {{ template "kube-state.name" . }}
    chart: {{ template "kube-state.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - nodes # Don't need
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes # May not need / users may not have
  - namespaces # Don't need
  - endpoints
  verbs: ["list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets # Don't need
  - deployments
  - replicasets
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["list", "watch"]
{{- end }}
