################################
## Kube State Role/ClusterRole
#################################
{{- $singleNamespace := .Values.global.singleNamespace }}
{{- if .Values.global.rbacEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if $singleNamespace }}Role{{ else }}ClusterRole{{ end }}
metadata:
  name: {{ template "kube-state.fullname" . }}
  labels:
    tier: monitoring
    component: {{ template "kube-state.name" . }}
    chart: {{ template "kube-state.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - endpoints
  {{- if not $singleNamespace }}
  - nodes
  - namespaces
  - persistentvolumes
  {{- end }}
  verbs: ["list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - deployments
  - replicasets
  {{- if not $singleNamespace }}
  - daemonsets
  {{- end }}
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["list", "watch"]
{{- end }}
