################################
## NGINX Role/ClusterRole
#################################
{{- $singleNamespace := .Values.global.singleNamespace }}
{{- if .Values.global.rbacEnabled }}
kind: {{ if $singleNamespace }}Role{{ else }}ClusterRole{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    tier: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - pods
      - secrets
      {{- if not $singleNamespace }}
      - nodes
      {{- end }}
    verbs:
      - list
      - watch
  {{- if not $singleNamespace }}
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  {{- end }}
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  {{- if not $singleNamespace }}
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  {{- end }}
{{- end }}
