################################
## Prometheus ClusterRole
#################################
{{- $singleNamespace := .Values.global.singleNamespace }}
{{- if .Values.global.rbacEnabled }}
kind: {{ if $singleNamespace }}Role{{ else }}ClusterRole{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    tier: monitoring
    component: {{ template "prometheus.name" . }}
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes" #Don't need
      - "nodes/proxy" #Don't need
      - "services"
      - "endpoints"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
  {{- if not .Values.global.singleNamespace }}
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - "get"
  {{- end }}
{{- end }}
