################################
## Astronomer Commander Role/ClusterRole
#################################
{{- $singleNamespace := .Values.global.singleNamespace }}
{{- if and .Values.global.rbacEnabled }}
kind: {{ if $singleNamespace }}Role{{ else }}ClusterRole{{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-commander
  labels:
    tier: houston
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
    - ""
  resources:
  - secrets
  - persistentvolumeclaims
  - namespaces #Don't need
  verbs:
  - create
  - get
  - update
  - delete
  - deletecollection
{{- end }}
